sudo: false
language: python
python: 2.7

cache: false

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=cover
  - TOX_ENV=pep8


install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox -e $TOX_ENV

# Don't fail on trunk versions.
matrix:
  allow_failures:
    - env: TOX_ENV=pypy
    - env: TOX_ENV=py27
    - env: TOX_ENV=py33
    - env: TOX_ENV=py34
  include:
    - python: 3.5
      env: TOX_ENV=py35
